## Simple workflow for deploying static content to GitHub Pages and test1
name: Deploy static content to Pages

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/teste1-AutoDeployTrigger-b748f45b-c30f-4a68-b7cc-489ce5951cfd.yml'

  # Allow manual trigger 
  workflow_dispatch:      

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
    # Single deploy to development environment
  deploy:
    environment:
      name: desenvolvimento
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # crie um job que realiza deploy em webapps Azure
  deploy-azure:
    needs: deploy
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Permite comentários em PRs
          action: "upload"
          #### Ajuste os caminhos abaixo conforme sua estrutura ####
          app_location: "/"   # Pasta onde está seu index.html
          api_location: ""    # Se não houver backend, deixe vazio
          output_location: "" # Para HTML puro, não há pasta de build